#!/bin/bash
set -e

## Env
source .env
source spin

LIVE_PATH="$(cd "$(dirname "$0")" && pwd)"

# Set hostname
echo "${HOST_NAME}" > /etc/hostname
printf "
127.0.0.1   localhost
::1         localhost
127.0.1.1   %s
" "${HOST_NAME}" >>/etc/hosts

# Set language
sed -i 's/#en_US\.UTF-8 UTF-8/en_US\.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf

# Update mirrorlist
cp -f "${LIVE_PATH}/includes/mirrorlist" /etc/pacman.d/mirrorlist
sed -i ':a;N;$!ba;s/#[multilib]\n#Include = \/etc\/pacman.d\/mirrorlist/[multilib]\nInclude = \/etc\/pacman.d\/mirrorlist/g' /etc/pacman.conf

# Set network time
ln -sf /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime
hwclock --systohc --utc
timedatectl set-ntp true

# Boot setup
mkinitcpio -P
bootctl --path=/boot install
cp -f "${LIVE_PATH}/includes/boot-loader.conf" /boot/loader/loader.conf
cp -f "${LIVE_PATH}/includes/arch.conf" /boot/loader/entries/arch.conf
sed -i "s/%ROOT_LABEL%/${ROOT_LABEL}/g" /boot/loader/entries/arch.conf

source install/create-user
source arch-package