#!/bin/bash
set -e

## Env
source .env
source spin
LIVE_PATH="$( cd "$( dirname "$0" )" && pwd )"
echo 1
if [[ ${INSTALL_BASE} -ne 0 ]]; then
    echo 1.1
    source install/base-pkg
fi
echo 2
if [[ ${INSTALL_KDE} -ne 0 ]]; then
    echo 2.1
    source install/plasma
fi
echo 3
if [[ ${INSTALL_PHP_STORM} -ne 0 ]] || [[ ${INSTALL_DATA_GRIP} -ne 0 ]] || [[ ${INSTALL_INTELIJ_IDEA} -ne 0 ]] || [[ ${INSTALL_WEB_STORM} -ne 0 ]]; then
    echo 3.1
    source install/intelij
fi
echo 4
if [[ ${INSTALL_DOCKER} -ne 0 ]]; then
    echo 4.1
    source install/docker
fi
echo 5
if [[ ${INSTALL_OH_MY_ZSH} -ne 0 ]]; then
    echo 5.1
    source install/oh-my-zsh
fi

echo "Arch Linux install package done! <<<<<<<<<<<<<<<<<< VooThanhArch"
